#index:
#    path: /
#    controller: App\Controller\DefaultController::index

# the "app_lucky_number" route name is not important yet
app_home:
  path: /
  controller: App\Controller\HomeController::home
